#ifndef PROTOCOL_COMMON_H
#define PROTOCOL_COMMON_H

#define EVT_USER_FINISHED "USER_FINISHED"
#define EVT_USER_MISSED   "USER_MISSED"
#define EVT_USER_CHECKEDIN "USER_CHECKEDIN"

#define CMD_CONTINUE_RESPONSE "CONTINUE_RESPONSE"
#define MSG_CONTINUE_PROMPT    "CONTINUE_PROMPT"

#endif // PROTOCOL_COMMON_H
