# protocol_common.py
# shared command/event strings for server and device modules

CMD_GETSTATUS = "GETSTATUS"
CMD_STARTCOUNTDOWN = "STARTCOUNTDOWN"
CMD_STOPCOUNTDOWN = "STOPCOUNTDOWN"
CMD_CONTINUE_RESPONSE = "CONTINUE_RESPONSE"

EVT_USER_FINISHED = "USER_FINISHED"
EVT_USER_MISSED = "USER_MISSED"
EVT_USER_CHECKEDIN = "USER_CHECKEDIN"

MSG_CONTINUE_PROMPT = "CONTINUE_PROMPT"

__all__ = [
    "CMD_GETSTATUS",
    "CMD_STARTCOUNTDOWN",
    "CMD_STOPCOUNTDOWN",
    "CMD_CONTINUE_RESPONSE",
    "EVT_USER_FINISHED",
    "EVT_USER_MISSED",
    "EVT_USER_CHECKEDIN",
    "MSG_CONTINUE_PROMPT",
]
